apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: justic
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          # [수정] 스냅샷(RDB) 및 AOF 기능을 모두 비활성화하는 인자 추가
          args: 
            - "--save"
            - ""
            - "--appendonly"
            - "no"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
